const orders = [
  {
    order: 1001,
    total: 150,
    customer: "John Doe",
    status: "Shipped",
    paymentMethod: "Gcash",
    date: "2023-01-15",
  },
  {
    order: 1002,
    total: 120,
    customer: "Jane Smith",
    status: "Processing",
    paymentMethod: "Paypal",
    date: "2023-02-03",
  },
  {
    order: 1003,
    total: 200,
    customer: "Mike Johnson",
    status: "Completed",
    paymentMethod: "Cash on delivery",
    date: "2023-03-10",
  },
  {
    order: 1004,
    total: 80,
    customer: "Sarah Brown",
    status: "Processing",
    paymentMethod: "Paypal",
    date: "2023-04-22",
  },
  {
    order: 1005,
    total: 250,
    customer: "Alex Carter",
    status: "Shipped",
    paymentMethod: "Gcash",
    date: "2023-05-05",
  },
  {
    order: 1006,
    total: 130,
    customer: "Emily Davis",
    status: "Completed",
    paymentMethod: "Cash on delivery",
    date: "2023-06-18",
  },
  {
    order: 1007,
    total: 180,
    customer: "Robert Lee",
    status: "Processing",
    paymentMethod: "Cash on delivery",
    date: "2023-07-01",
  },
  {
    order: 1008,
    total: 160,
    customer: "Olivia White",
    status: "Shipped",
    paymentMethod: "Gcash",
    date: "2023-08-14",
  },
  {
    order: 1009,
    total: 90,
    customer: "Liam Miller",
    status: "Completed",
    paymentMethod: "Paypal",
    date: "2023-09-27",
  },
  {
    order: 1010,
    total: 210,
    customer: "Ava Wilson",
    status: "Shipped",
    paymentMethod: "Gcash",
    date: "2023-10-09",
  },
];

export default orders;
